# .github/actions/ensure-ui/action.yml
name: 'EnsureUI Testing Action'
description: 'Automated UI testing for pages marked with // ensureUI comment'
inputs:
  deployment-url:
    description: 'URL of the deployed application'
    required: true
  github-token:
    description: 'GitHub token for PR comments'
    required: true
  timeout:
    description: 'Page load timeout in seconds'
    required: false
    default: '15'

outputs:
  results:
    description: 'Test results in JSON format'
    value: ${{ steps.run-tests.outputs.results }}

runs:
  using: 'composite'
  steps:
    - name: Setup EnsureUI environment
      run: npm install --no-save playwright @playwright/test
      working-directory: ${{ github.action_path }}

    - name: Install Playwright browsers
      run: npx playwright install chromium
      working-directory: ${{ github.action_path }}

    - name: Create screenshots directory
      run: mkdir -p screenshots

    - name: Run EnsureUI tests
      id: run-tests
      run: node ensure-ui.js
      working-directory: ${{ github.action_path }}
      env:
        DEPLOYMENT_URL: ${{ inputs.deployment-url }}
        TIMEOUT: ${{ inputs.timeout }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        PR_NUMBER: ${{ github.event.number }}
